// <auto-generated />
namespace LND.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addmorepricein : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmorepricein));
        
        string IMigrationMetadata.Id
        {
            get { return "201912251912185_addmorepricein"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
